### PR TITLE
Did some refactoring

### PR DESCRIPTION
**Pull request by SlowLogicBoy**
Basically refactoring:
Moved some stuff to WebDriverClass since they did web stuff (however some still left)
Solved one recursion
Did some renaming to suit .net naming conventions.

### CODE REVIEW

**Comment by JackRyder** [comment]
Will need to test this when I get time, I'm planning on trying to move stuff to .NET standard soon though, so need to figure out what's compatible

**Comment by SlowLogicBoy** [comment]
* there is only AvaloniaUI for .Net Standard as UI frameworks so, you would need to get rid of WinForms.
* I don't know if your player would be compatible. I just do Process.Start(urlToVideo), and my default player starts playing that video (vlc in my case).

* PhantomJS  well, you might be screwed, of course you could use some other JS engine, that would be compatible however don't know any yet, unless also use Process class and manage them platform specific.

For now I do not recommend moving to .net standard, but you can definitely work towards this.

**Comment by JackRyder** [comment]
I don't mean moving everything in that way, but I mean creating class libs that are compatible across the board.

**Comment by SlowLogicBoy** [comment]
Ah yea, that would be great

**Pull request merged**
